services:
  game:
    build: .
    ports:
      - '127.0.0.1:8000:8000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      VIRTUAL_HOST: siege.janczechowski.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: siege.janczechowski.com
    networks:
      - nginx-proxy
      - default

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - BASE_URL=http://game:8000
    profiles:
      - test

  assets:
    image: python:3.13-slim
    volumes:
      - ../assets:/assets
      - ./public/assets:/app/public/assets
    working_dir: /assets
    command: >-
      sh -c "pip install uv --quiet && uv run unpack.py"
    profiles:
      - tools

networks:
  nginx-proxy:
    external: true
